/**
 * Copyright Notice 
 * 
 * COPYRIGHT© 2015 Build 82. All rights reserved. No part of this software
 * and constituent code may be reproduced in any form, including video recording, 
 * photocopying, downloading, broadcasting or transmission electronically, without 
 * prior written consent of Build 82. Copyright protection includes output
 * generated by this software as displayed in print or in digital form, such as 
 * icons, interfaces, and the like.
 * 
 * Content Warranty 
 * 
 * The information in this document is subject to change without notice. THIS 
 * DOCUMENT IS PROVIDED "AS IS" AND BUILD 82 MAKES NO WARRANTY, EXPRESS, 
 * IMPLIED, OR STATUTORY, INCLUDING BUT NOT LIMITED TO ALL WARRANTIES OF 
 * MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT. 
 * Build 82 shall not be liable for errors contained herein or for 
 * incidental or consequential damages in connection with the furnishing, 
 * performance or use of this material.
 */

define( 
    function() {
		return {
			Link: [
				{url: 'index.html', name: 'Application', type: 'local', 
					description: "The International Flag of Earth - Image Generator application."
				},
				{url: 'instructions.html', name: 'Instructions', type: 'local', 
					description: "A detailed description of the application interface and controls."
				},
				{separator: true},
				{url: 'https://en.wikipedia.org/wiki/Flag_of_the_Earth', name: 'Wikipedia : Flag of the Earth', type: 'website',
					description: "Wikipedia's article on flags of earth contains a brief discussion about flags representing Earth and mentions\n\
					short history of other proposals."
				},
				{url: 'https://www.facebook.com/ifoearth', name: 'Facebook : International Flag of Earth - Image Generator', type: 'website',
					description: "The Facebook Page of iFlag of Earth where poeople can discuss the application, share their overlays, and \n\
					share the application with their friends & followers."
				},
				{url: 'http://nosdare.gliscam.us', name: 'Internationalis Vexillum Terrae', type: 'mirror',
					description: "The Latin mirror of iFlag of Earth."
				},
				{separator: true},
				{url: 'https://facebook.com', name: 'Facebook, Inc.', type: 'organization', description: ""},
				{url: 'https://twitter.com', name: 'Twitter, Inc.', type: 'organization', description: ""},
				{url: 'https://dropbox.com', name: 'Dropbox Inc.', type: 'organization', description: ""}
			]
		};
	}
);