/**
 * Copyright Notice 
 * 
 * COPYRIGHT© 2015 Build 82. All rights reserved. No part of this software
 * and constituent code may be reproduced in any form, including video recording, 
 * photocopying, downloading, broadcasting or transmission electronically, without 
 * prior written consent of Build 82. Copyright protection includes output
 * generated by this software as displayed in print or in digital form, such as 
 * icons, interfaces, and the like.
 * 
 * Content Warranty 
 * 
 * The information in this document is subject to change without notice. THIS 
 * DOCUMENT IS PROVIDED "AS IS" AND BUILD 82 MAKES NO WARRANTY, EXPRESS, 
 * IMPLIED, OR STATUTORY, INCLUDING BUT NOT LIMITED TO ALL WARRANTIES OF 
 * MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT. 
 * Build 82 shall not be liable for errors contained herein or for 
 * incidental or consequential damages in connection with the furnishing, 
 * performance or use of this material.
 */

define(['dojo/request/xhr',
		'dojo/io-query'],
    function(xhr, ioQuery) {
		var config = {
			appKey: '6sch126sunjawc5',
			authorizeBase: 'https://www.dropbox.com/1/oauth2/authorize',
			redirectUrl: 'http://localhost:8383/flagofearth/index.html'
		},
				
		data = {
			
		},
		
		handleAuthorize_Success = function() {
		
		},
		handleAuthorize_Error = function() {

		};
		
        console.log('Dropbox ready');

        return {
			Authorize: function() {
				var dropboxUrl = config.authorizeBase + '?' + ioQuery.objectToQuery({
					client_id: config.appKey,
					response_type: 'token',
					redirect_uri: config.redirectUrl
				});
		
				window.location = dropboxUrl;
			}
		};
    } 
);